services:
  web-app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8001:8000"
    volumes:
        - ./service:/service
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
